#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Prettier + ESLint tasks
npx lint-staged

# Section for git-secrets
if ! command -v git-secrets &> /dev/null
then
    echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi

# Initialize git-secrets configuration
echo "Initializing git-secrets..."
git-secrets --register-aws > /dev/null

# Scans all files that are about to be committed
echo "Running git-secrets..."
git-secrets --pre_commit_hook -- "$@"
