#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Conventional Commits
npx --no -- commitlint --edit ${1}

# Section for git-secrets
if ! command -v git-secrets &> /dev/null
then
    echo "git-secrets is not installed. Please run 'brew install git-secrets' or visit https://github.com/awslabs/git-secrets#installing-git-secrets"
    exit 1
fi

# Initialize git-secrets configuration
echo "Initializing git-secrets..."
git-secrets --register-aws > /dev/null

# Determines if merging in a commit will introduce tainted history
echo "Running git-secrets..."
git-secrets --prepare_commit_msg_hook -- "$@"
